### PR TITLE
add lamp locations

### PR DESCRIPTION
**Pull request by luxeder**

### CODE REVIEW

**Comment by neophob** [comment]
Thank @luxeder for your work, really like it!

I just checked the lamp positions and compared it with the manual, see https://imgur.com/a/IqeIJ34

some inputs:

- lamps 54 -56 it looks like some lamps are off there
- lamp 25 is misplaced
- what are the 4 lamps middle left - the are not visible in the manual

I placed lamp 88 and 87 on the bottom with the correct x offset. 

where do you get the information about the lamp color from? either I used pinmame source (https://github.com/vpinball/pinmame/blob/master/src/wpc/sims/wpc/prelim/mb.c - its not here yet) or used some you tube videos.

do you mind check/update the lamp positions?

thanks again for your help!
Cheers

**Comment by luxeder** [comment]
I'll correct lamps 18, 25, 52, 55 this weekend. The 4 lamps in the middle left are present in the actual game, they show the progress of one of the objectives in the game (Creature). I got the colors from a MB at the place I work, so unless I messed some of them up, they should be more or less correct.

**Comment by neophob** [comment]
@luxeder any inputs from your side? I'm still waiting to merge your PR ;)

**Comment by tanseydavid** [comment]
Did this PR get merge into MASTER?  It does not appear as though it did...

**Comment by neophob** [comment]
nop, there are some issues, see above

**Pull request closed without merging**
